[package]
name = "adventofcode-rust-2019"
version = "0.1.0"
authors = ["Toon Spin <toon.spin@gmail.com>"]
edition = "2021"

[dependencies]
nom = { version = "7" }
intcode = { git = "ssh://git@github.com:22/ToonSpin/intcode.git", branch = "main" }